// Builds src/content/registry.generated.js — the meta of every content page
// under src/content/pages/ — and validates each page against
// src/content/schema.js. The registry is what the router, the head tags,
// the sitemap and llms.txt read; the page bodies stay in their own lazily
// loaded chunks. Runs first in `npm run build`; run it by hand
// (`npm run content`) after adding or editing a page. The generated file is
// committed, and a test fails if it's out of date. `--dry` only validates.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pagesDir = path.join(root, 'src', 'content', 'pages');
const outFile = path.join(root, 'src', 'content', 'registry.generated.js');

const { validatePage, SECTIONS } = await import(pathToFileURL(path.join(root, 'src/content/schema.js')).href);

function walk(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((d) => {
    const p = path.join(dir, d.name);
    if (d.isDirectory()) return walk(p);
    return d.name.endsWith('.js') && !d.name.endsWith('.test.js') ? [p] : [];
  });
}

const entries = [];
const problems = [];
for (const file of walk(pagesDir).sort()) {
  const rel = path.relative(root, file).split(path.sep).join('/');
  const page = (await import(pathToFileURL(file).href)).default;
  problems.push(...validatePage(page, rel));
  if (!page?.meta) continue;
  const { path: p, section, name, title, description, updated, published, station } = page.meta;
  entries.push({
    path: p,
    section,
    name,
    title,
    description,
    updated,
    published,
    station: station ?? null,
    og: SECTIONS[section]?.og ?? 'default',
    source: rel,
  });
}

const dupes = entries.map((e) => e.path).filter((p, i, all) => all.indexOf(p) !== i);
if (dupes.length) problems.push(`duplicate paths: ${[...new Set(dupes)].join(', ')}`);
if (problems.length) {
  console.error(`content: ${problems.length} problem(s)\n  ${problems.join('\n  ')}`);
  process.exit(1);
}

entries.sort((a, b) => a.path.localeCompare(b.path));
const body = `// Generated by scripts/content-index.mjs from src/content/pages/ — do not edit.
// Run \`npm run content\` after adding or changing a content page.
export const CONTENT_PAGES = ${JSON.stringify(entries, null, 2)};
`;
const check = process.argv.includes('--check');
// --dry: validate every page and report, but write nothing (safe to run while
// other pages are being edited).
if (process.argv.includes('--dry')) {
  console.log(`content: ${entries.length} pages valid`);
  process.exit(0);
}
// Compare without line-ending noise (git may check the file out with CRLF).
const current = fs.existsSync(outFile)
  ? fs.readFileSync(outFile, 'utf8').replace(/\r\n/g, '\n')
  : '';
if (check) {
  if (current !== body) {
    console.error('content: registry.generated.js is out of date — run `npm run content`');
    process.exit(1);
  }
  console.log(`content: registry up to date (${entries.length} pages)`);
} else {
  if (current !== body) fs.writeFileSync(outFile, body);
  console.log(`content: ${entries.length} pages indexed`);
}
